mode:
    mode: 'train'
    model_zoo: 'BCZ'
    multiprocessing_distributed: False
    dist_url: tcp://127.0.0.1:2345
    num_threads: 1
    do_online_eval: True
    parameter_path: ''
train:
    dim_x: 10
    dim_z: ''
    dim_a: 10
    dim_gt: 10
    num_ensemble: 32
    win_size: 32
    seed: 0
    model_name: 'BCZ_v1.0'
    dataset: 'Duck'
    sensor_len: 2
    channel_img_1: 3
    channel_img_2: ''
    input_size_1: 77
    input_size_2: ''
    input_size_3: ''
    data_path: [
        '/tf/datasets/pick_duck/pick_duck_1',
        '/tf/datasets/pick_duck/pick_duck_2',
    ]
    batch_size: 64
    num_epochs: 2000
    learning_rate: 1e-4
    weight_decay: 1e-6
    adam_eps: 1e-3
    log_freq: 10
    eval_freq: 200
    save_freq: 200
    log_directory: './experiments'
    loss: 'mse'
test:
    dim_x: 10
    dim_z: ''
    dim_a: 10
    dim_gt: 10
    num_ensemble: 32
    win_size: 32
    model_name: 'BCZ_v1.0'
    data_path: [
        '/tf/datasets/pick_duck/pick_duck_1',
    ]
    sensor_len: 2
    channel_img_1: 3
    channel_img_2: ''
    input_size_1: 77
    input_size_2: ''
    input_size_3: ''
    checkpoint_path_1: ''
    checkpoint_path_2: ''
    dataset: 'Duck'
optim:
    optim: 'adamw'
    lr_scheduler: 'polynomial_decay'